### ISSUE TITLE
Market Data Client

### ISSUE THREAD

**Issue by epsilonsized** [zetamarkets/sdk#66]
### **Bounty Description**

A market data client leveraging the Zeta SDK that is able to provide real-time websocket market data APIs mirroring that of CeFi exchanges for Zeta.

### Requirements

Submissions will be reviewed on an on-going basis. Please include the following in your submission:

* Github repo (the cleaner the better!)
* Demo of the client running successfully (where possible)

### Criteria

We will look at:

* Quality of the github repo
* Implementation of the client

### Deadline

* All submissions will reviewed by 01/03/2022 - any submissions after this will be ineligible for a prize from this bounty program.

### Resources

An example of this implementation can be found in the Mango Bowl and Serum Vial repos.
https://github.com/tardis-dev/serum-vial
https://github.com/tardis-dev/mango-bowl

**Comment by Jac0xb** [comment]
Is this no longer needed @epsilonsized ?
