### ISSUE TITLE
Risk Dashboard

### ISSUE THREAD

**Issue by epsilonsized** [zetamarkets/sdk#68]
### **Bounty Description**

Add a dashboard that is able to perform scenario analysis on expected profit and loss, as well as margin requirements in different scenarios. Should be relevant to the user in question. 

### Requirements
* Based on user connected wallet display risks
* Allow user to enter in a wallet address to fetch another accounts risks
* Display core account metrics (Account balance, Unrealised PnL, Initial Margin, Maintenance Margin)
* Fetch user positions
* Fetch greeks for user positions
* Fetch greeks for user aggregate portfolio
* Given portfolio lets user input (Drag) underlying price to see how account metrics and greeks change
* Given a position let user input (Drag) underlying price to see how account metrics and greeks change

Submissions will be reviewed on an on-going basis. Please include the following in your submission:

* Github repo (the cleaner the better!)
* Demo of the dashboard (where possible)

### Criteria

We will look at:

* Quality of the github repo
* Implementation of the dashboard

### Deadline

* All submissions will reviewed by 01/03/2022 - any submissions after this will be ineligible for a prize from this bounty program.

### Resources

Example dashboard is here:
https://trade.mango.markets/risk-calculator

**Comment by Prinkesh** [comment]
Hi is this removed from bounty ?  i don't see it anymore on the zeta feature bounties dashboard .
