### ISSUE TITLE
Public Leaderboard

### ISSUE THREAD

**Issue by epsilonsized** [zetamarkets/sdk#70]
### **Bounty Description**

Add a leaderboard for PnL (dollars and percentage) which is able to display PnL rankings across a range of time periods, and additionally recognises Solana Name Service addresses.

### Requirements
* Application factors in user deposits and withdraws so it can isolate PnL
* Based on user Unrealised PnL, Account Balance and Deposit Withdraws calculate total PnL given user account
* Have a table of user accounts - sortable by PnL
* In table display unrealised PnL too (perhaps in brackets or in another column)
* Let users search address
* Display users rank and historical PnL based on connected wallet at top
* Add a filter for PnL over different time ranges.

Submissions will be reviewed on an on-going basis. Please include the following in your submission:

* Github repo (the cleaner the better!)
* Demo of the leaderboard (where possible)

### Criteria

We will look at:

* Quality of the github repo
* Implementation of the leaderboard

### Deadline

* All submissions will reviewed by 01/03/2022 - any submissions after this will be ineligible for a prize from this bounty program.

### Resources

**Comment by akshaydhayal** [comment]
Hey, is this still active?

**Comment by akshaydhayal** [comment]
Hey, is this still active?

**Comment by 0xtristan** [comment]
Already shipped sorry: https://mainnet.zeta.markets/leaderboard
